version: "3.7"
services:
  db:
    image: "postgres:latest"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db # add all dependant container
    environment:
      RAILS_ENV: development

volumes:
  postgres: # named volume

